services:
  - type: web
    name: pokedex
    env: node
    buildCommand: NODE_OPTIONS="--max-old-space-size=256" npm run build:render
    startCommand: NODE_OPTIONS="--max-old-space-size=256" npm run start:prod
    plan: free
    region: ohio
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=256"